"""Contract tests for the shared data-provenance strip (P37-02).

Three honesty surfaces were missing or fragmented before this:

- `meta.candidatesSource` was emitted by the API and consumed by NOTHING — the
  backend labelled its own sample fallback honestly and the UI dropped it;
- the Rule 11.9.4 section-fallback banner lived only inside V3, so V1/V2/V4
  rendered sample markets and news with no warning at all;
- `meta.pipelineHealth` (Rule 15.10) had no UI surface, which is why P37-01 was
  held at BACKEND COMPLETE rather than DONE.

Two kinds of test here, deliberately. The structural ones assert there is ONE
implementation mounted once in the shell — four call sites can drift, one mount
cannot. The behavioural ones EXECUTE the resolvers in node against real payload
shapes, including a payload generated by the actual backend producer, so a
field rename on either side fails loudly instead of silently rendering "real"
over sample data. Grep-only assertions would pass on a strip that renders
nothing.
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

import pytest  # noqa: E402

FRONTEND = PROJECT_ROOT / "frontend"
STRIP = FRONTEND / "src" / "htr-provenance.jsx"
VARIANTS = ("src/htr-v1.jsx", "src/htr-v2.jsx", "src/htr-v3.jsx", "src/htr-v4.jsx")


def _read(rel: str) -> str:
    return (FRONTEND / rel).read_text(encoding="utf-8")


def _all_frontend_sources() -> dict[str, str]:
    out: dict[str, str] = {}
    for p in sorted(FRONTEND.rglob("*.jsx")) + sorted(FRONTEND.glob("*.html")) + sorted(FRONTEND.rglob("*.js")):
        if "_backup" in str(p):
            continue
        out[p.relative_to(FRONTEND).as_posix()] = p.read_text(encoding="utf-8")
    return out


# ── structural: one implementation, one mount, no variant copies ─────────


def test_the_strip_has_exactly_one_implementation():
    defined_in = [rel for rel, text in _all_frontend_sources().items()
                  if "function DataProvenanceStrip" in text]
    assert defined_in == ["src/htr-provenance.jsx"], (
        f"DataProvenanceStrip must be defined exactly once; found in {defined_in}")


def test_the_strip_is_mounted_once_in_the_shell_above_main():
    """Mounted in the app shell, not called from each variant.

    Every variant then gets it BY CONSTRUCTION. This is strictly stronger than
    four variants each remembering to call a shared component, which is the
    arrangement that let the V3-only fallback banner exist in the first place.
    """
    index = _read("index.html")
    assert index.count("<DataProvenanceStrip />") == 1
    mount = index.index("<DataProvenanceStrip />")
    main = index.index('<main className="app-main htr">')
    assert mount < main, "the strip must render above <main>, which hosts all four variants"


def test_no_variant_reimplements_the_provenance_logic():
    """Rule 11.7 — a variant-local copy is how these three surfaces diverged."""
    for rel in VARIANTS:
        text = _read(rel)
        for token in ("candidatesSource", "pipelineHealth", "__degraded"):
            assert token not in text, (
                f"{rel} references {token!r}: provenance belongs to the one shared "
                "strip. Four copies drift; one does not.")
        # Naming it in a comment is fine and useful; RENDERING it is the copy.
        assert "<DataProvenanceStrip" not in text, (
            f"{rel} renders its own strip instance; the shell mounts the only one")


def test_the_v3_only_fallback_banner_is_gone():
    """It was the concrete instance of the divergence being prevented."""
    v3 = _read("src/htr-v3.jsx")
    assert "示例数据：" not in v3
    strip = STRIP.read_text(encoding="utf-8")
    assert "示例数据：" in strip, "the banner must survive the move, not be deleted"


def test_the_strip_script_is_loaded_before_the_variants():
    index = _read("index.html")
    strip_tag = index.index("src/htr-provenance.jsx")
    for rel in VARIANTS:
        assert strip_tag < index.index(rel), f"{rel} loads before the strip"


def test_the_component_list_is_not_collapsible_or_truncated():
    """Rule 15.10.7 — showing the aggregate without its components recreates the
    defect one level up, and a collapsed or truncated list is a way of doing
    exactly that while looking compliant."""
    strip = STRIP.read_text(encoding="utf-8")
    body = strip[strip.index("data-htr-health-components"):]
    assert "expanded" not in body, "the component list must not sit behind a collapse guard"
    assert ".slice(" not in body and "+N" not in body, "the list must not be truncated"


# ── behavioural: actually run the resolvers ──────────────────────────────


def _pure_js_prefix() -> str:
    """The strip's plain-JS half (resolvers + tables), before any JSX."""
    text = STRIP.read_text(encoding="utf-8")
    return text[:text.index("function HtrProvenancePill")]


def _run_js(body: str) -> dict:
    node = shutil.which("node")
    if not node:  # pragma: no cover - environment dependent
        pytest.skip("node not available; strip behaviour not executed")
    script = _pure_js_prefix() + "\n" + body
    # encoding is explicit: the strip's labels are Chinese, and letting
    # Windows decode node's stdout as cp932 fails before any assertion runs.
    proc = subprocess.run([node, "--input-type=module", "-e", script],
                          capture_output=True, text=True, timeout=60,
                          encoding="utf-8", errors="replace")
    assert proc.returncode == 0, f"node failed: {proc.stderr[-2000:]}"
    return json.loads(proc.stdout)


@pytest.mark.parametrize("meta,expected_real,label", [
    (None, False, "no meta at all"),
    ({}, False, "meta without the field"),
    ({"candidatesSource": "sample"}, False, "explicit sample"),
    ({"candidatesSource": ""}, False, "empty string"),
    ({"candidatesSource": "some_future_producer"}, False, "unrecognised producer"),
    ({"candidatesSource": "screener_v2"}, True, "the real screener"),
])
def test_only_an_explicit_screener_v2_counts_as_real(meta, expected_real, label):
    """Fail-closed: "real" is a positive assertion the payload must make.

    The offline mock has no `candidatesSource` at all, and that is precisely
    the case where the screen must not look authoritative.
    """
    out = _run_js(f"console.log(JSON.stringify(resolveCandidateSource({json.dumps(meta)})))")
    assert out["real"] is expected_real, label
    if not expected_real:
        assert "SAMPLE" in out["label"]


def test_source_is_never_derived_from_how_many_candidates_loaded():
    """A populated array proves the mock loaded, not that the screener ran.

    The offline path fills `candidates` from the mock fixture, so any
    length- or emptiness-based check would report that fixture as real data.
    The verdict must come from the declared field and nothing else.
    """
    js = _pure_js_prefix()
    fn = js[js.index("function resolveCandidateSource"):]
    fn = fn[:fn.index("\n}") + 2]
    for forbidden in (".length", "candidates.", "candidates[", "HTR_DATA", "Array."):
        assert forbidden not in fn, (
            f"resolveCandidateSource references {forbidden!r}; the source verdict "
            "must not depend on how many rows happened to load")
    # And it is a positive match on the declared producer, not a negative one:
    # `!== "sample"` would call any future producer real by default.
    assert 'source === "screener_v2"' in fn


def test_the_offline_mock_meta_declares_no_source_so_it_renders_as_sample():
    """The mock has no `candidatesSource`, and that is the point.

    An offline render must not look authoritative. This pins the fixture, so
    someone adding `candidatesSource: "screener_v2"` to the mock to silence the
    banner breaks a test instead of silently faking provenance.
    """
    mock = _read("src/htr-data.js")
    assert "candidatesSource" not in mock
    out = _run_js("console.log(JSON.stringify(resolveCandidateSource({"
                  "asof: '2026-05-24 10:32:14 JST', tradeDate: '2026-05-24'})))")
    assert out["real"] is False


def test_sample_state_does_not_soften_on_a_successful_http_response():
    """A 200 that served the sample fixture is the case being warned about."""
    out = _run_js(
        "const ok = resolveCandidateSource({candidatesSource: 'sample', "
        "tradeDate: '2026-08-10', asof: '2026-08-11T19:30:01+09:00'});"
        "console.log(JSON.stringify(ok))")
    assert out["real"] is False
    assert "SAMPLE" in out["label"]


@pytest.mark.parametrize("meta,expected", [
    (None, "unknown"),
    ({}, "unknown"),
    ({"pipelineHealth": None}, "unknown"),
    ({"pipelineHealth": {}}, "unknown"),
    ({"pipelineHealth": {"status": "unknown"}}, "unknown"),
    ({"pipelineHealth": {"status": "not_a_real_state"}}, "unknown"),
    ({"pipelineHealth": {"status": "healthy"}}, "healthy"),
    ({"pipelineHealth": {"status": "degraded"}}, "degraded"),
    ({"pipelineHealth": {"status": "failed"}}, "failed"),
])
def test_health_falls_back_to_unknown_never_to_healthy(meta, expected):
    out = _run_js(f"console.log(JSON.stringify(resolvePipelineHealth({json.dumps(meta)})))")
    assert out["status"] == expected


def test_unknown_health_renders_as_a_warning_not_as_green():
    """A missing answer and a good answer must never look the same."""
    out = _run_js("console.log(JSON.stringify(HTR_HEALTH_TONE))")
    assert out["unknown"]["tone"] == "warn"
    assert out["unknown"]["tone"] != out["healthy"]["tone"]
    assert out["healthy"]["tone"] == "ok"
    assert out["failed"]["tone"] == "bad"


def test_every_degraded_component_survives_the_resolver():
    payload = {"pipelineHealth": {
        "status": "degraded",
        "asof": "2026-08-10",
        "summary": "degraded: a, b, c",
        "degradedComponents": [
            {"component": "a", "code": "a.x", "perishable": False},
            {"component": "b", "code": "b.y", "perishable": True},
            {"component": "c", "code": "c.z", "perishable": False},
        ],
    }}
    out = _run_js(f"console.log(JSON.stringify(resolvePipelineHealth({json.dumps(payload)})))")
    assert [c["code"] for c in out["components"]] == ["a.x", "b.y", "c.z"]
    assert out["asof"] == "2026-08-10"


def test_a_malformed_component_list_degrades_to_empty_not_a_crash():
    out = _run_js(
        "console.log(JSON.stringify(resolvePipelineHealth("
        "{pipelineHealth: {status: 'degraded', degradedComponents: 'oops'}})))")
    assert out["components"] == []
    assert out["status"] == "degraded"


@pytest.mark.parametrize("degraded,expected", [
    ({}, []),
    ({"markets": True, "themes": True}, ["markets", "themes"]),
    ({"offline": True, "markets": True}, ["offline"]),
])
def test_section_fallback_list(degraded, expected):
    out = _run_js(f"console.log(JSON.stringify(fallbackSections({json.dumps(degraded)})))")
    assert out == expected


# ── producer/consumer contract, against the real backend payload ─────────


def test_the_strip_consumes_the_shape_the_backend_actually_emits():
    """End-to-end field-name contract.

    `_pipeline_health` and the strip are edited by different hands at different
    times. A rename on either side would otherwise surface as a silently empty
    badge -- the exact failure mode P37-02 exists to remove.
    """
    from api.serializers import _pipeline_health  # noqa: E402

    real = _pipeline_health(PROJECT_ROOT)
    out = _run_js(
        "console.log(JSON.stringify(resolvePipelineHealth("
        f"{json.dumps({'pipelineHealth': real, 'candidatesSource': 'screener_v2'})})))")

    assert out["status"] == real["status"]
    assert out["asof"] == real["asof"]
    assert len(out["components"]) == len(real["degradedComponents"])
    for got, want in zip(out["components"], real["degradedComponents"]):
        assert got["code"] == want["code"]
        assert got["perishable"] == want["perishable"]


def test_a_perishable_degradation_keeps_its_marker_through_the_resolver():
    from api.serializers import _pipeline_health  # noqa: E402

    real = _pipeline_health(PROJECT_ROOT)
    if not real.get("perishableDegraded"):
        pytest.skip("no perishable degradation in the current log")
    out = _run_js(
        "console.log(JSON.stringify(resolvePipelineHealth("
        f"{json.dumps({'pipelineHealth': real})})))")
    perishable = [c["component"] for c in out["components"] if c.get("perishable")]
    assert perishable == real["perishableDegraded"]


def test_the_perishable_marker_is_visually_distinct_and_says_why():
    """Rule 15.10.5 -- "we will catch it next run" is FALSE for these rows and
    true for every other row in the same list, so the marker has to carry the
    reason, not just a colour."""
    strip = STRIP.read_text(encoding="utf-8")
    assert 'data-htr-perishable="1"' in strip
    block = strip[strip.index("data-htr-perishable"):]
    block = block[:block.index("</span>")]
    assert "c.perishable &&" in strip
    assert "永久丢失" in strip


def test_source_health_and_panel_asof_are_all_visible():
    """Rule 15.10 / 11.9.2 -- a reading without its as-of is not a reading."""
    strip = STRIP.read_text(encoding="utf-8")
    for label in ("交易日", "健康 as-of", "面板刷新"):
        assert label in strip, f"missing as-of surface: {label}"
    assert "src.tradeDate" in strip and "health.asof" in strip and "meta.asof" in strip
