"""P37-04 — the journal is internally deterministic, not externally correct.

Why this module exists
----------------------
Rule 14.0 called the portfolio journal "the sole source of truth for live
positions, cash, and realized P&L", unqualified. That sentence is true of
*accounting* and false of *reality*: re-deriving from the same journal is
deterministic no matter how wrong the inputs were. On 2026-08-14 a cash event
read off a broken broker table (`譲渡益税還付金 991`) entered canonical cash,
the derived balance became JPY 287,794, the broker said JPY 287,068, and the
system published an official NAV of JPY 394,724 while calling itself
reconciled. Nothing in the code could have objected: no external evidence was
ever required.

So the contract these tests pin is that `reconciled` is a claim about the
OUTSIDE world and therefore needs outside evidence:

- the broker snapshot is the authority for cash, share counts and total assets;
- the broker's own identity (cash + Σ positions = total) must hold BEFORE any
  comparison, or the snapshot is not evidence of anything;
- a mismatch may produce a diagnostic, and must not produce an official NAV, a
  return metric, the word "reconciled", or a balancing adjustment;
- a cash event whose provenance is a screenshot / OCR / reconstructed text is
  PROVISIONAL until an account-level balance check passes, and provisional
  money never enters canonical cash.

Every broker fixture here is constructed independently, by hand, from figures a
broker page would show. None is derived from the journal under test - evidence
generated by the subject cannot test the subject, which is the same trap that
let a self-certifying witness and a mislocated CI workflow both pass.
"""
from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

import pytest  # noqa: E402

from hot_theme_rotator.portfolio.broker_reconciliation import (  # noqa: E402
    INCOMPARABLE_MARK_TIME,
    MISMATCH,
    MISSING_BROKER_SNAPSHOT,
    RECONCILED,
    STALE,
    BrokerPosition,
    BrokerSnapshot,
    BrokerSnapshotError,
    JournalView,
    canonical_cash,
    check_broker_identity,
    reconcile_against_broker,
)


# ---------------------------------------------------------------------------
# Independently constructed broker fixtures (never journal-derived)
# ---------------------------------------------------------------------------
def sbi_2026_08_14() -> BrokerSnapshot:
    """Typed from a broker account page: cash, share counts, marks, total."""
    return BrokerSnapshot(
        asof=date(2026, 8, 14),
        cash=287_068.0,
        positions={
            "1306.T": BrokerPosition(symbol="1306.T", qty=100, mark=437.8, value=43_780.0),
            "1568.T": BrokerPosition(symbol="1568.T", qty=60, mark=1052.5, value=63_150.0),
        },
        total_assets=393_998.0,
        source="sbi_web_manual",
        mark_time="2026-08-14T15:30+09:00",
    )


def journal_matching_the_broker() -> JournalView:
    return JournalView(
        asof=date(2026, 8, 14),
        cash=287_068.0,
        quantities={"1306.T": 100, "1568.T": 60},
        mark_time="2026-08-14T15:30+09:00",
    )


def journal_with_the_phantom_refund() -> JournalView:
    """The real 2026-08-14 state: +991 booked, broker says otherwise."""
    return JournalView(
        asof=date(2026, 8, 14),
        cash=287_794.0,
        quantities={"1306.T": 100, "1568.T": 60},
        mark_time="2026-08-14T15:30+09:00",
    )


# ---------------------------------------------------------------------------
# The broker's own identity comes first
# ---------------------------------------------------------------------------
def test_broker_identity_must_hold_before_anything_is_compared():
    snapshot = sbi_2026_08_14()
    identity = check_broker_identity(snapshot)
    assert identity["holds"] is True
    assert identity["cash"] == 287_068.0
    assert identity["positions_value"] == 106_930.0
    assert identity["total_assets"] == 393_998.0
    assert identity["residual"] == 0.0


def test_a_snapshot_that_does_not_add_up_is_not_evidence():
    """A mistyped or half-loaded page must not be able to reconcile anything."""
    broken = BrokerSnapshot(
        asof=date(2026, 8, 14),
        cash=287_068.0,
        positions={"1306.T": BrokerPosition("1306.T", 100, 437.8, 43_780.0)},
        total_assets=393_998.0,  # a position is missing, so this cannot balance
        source="sbi_web_manual",
        mark_time="2026-08-14T15:30+09:00",
    )
    identity = check_broker_identity(broken)
    assert identity["holds"] is False
    assert identity["residual"] == pytest.approx(63_150.0)

    verdict = reconcile_against_broker(journal_matching_the_broker(), broken)
    assert verdict.state == MISMATCH
    assert "identity" in (verdict.reason or "")
    assert verdict.may_write_official_nav is False


def test_position_value_must_match_qty_times_mark():
    """Catches a value column read from the wrong row."""
    with pytest.raises(BrokerSnapshotError, match="qty x mark"):
        BrokerPosition(symbol="1306.T", qty=100, mark=437.8, value=99_999.0).validate()


# ---------------------------------------------------------------------------
# reconciled requires external evidence
# ---------------------------------------------------------------------------
def test_reconciled_only_when_the_broker_agrees():
    verdict = reconcile_against_broker(journal_matching_the_broker(), sbi_2026_08_14())
    assert verdict.state == RECONCILED
    assert verdict.differences == []
    assert verdict.may_write_official_nav is True
    assert verdict.may_compute_return_metrics is True


def test_without_a_broker_snapshot_nothing_is_reconciled():
    """The defect in one line: no external evidence, so no external claim."""
    verdict = reconcile_against_broker(journal_matching_the_broker(), None)
    assert verdict.state == MISSING_BROKER_SNAPSHOT
    assert verdict.may_write_official_nav is False
    assert verdict.may_compute_return_metrics is False


def test_reconciled_cannot_be_derived_from_the_journal_alone():
    """A snapshot manufactured from the journal must be refused as evidence.

    This is the property that the old `reconciled_no_contradicting_evidence`
    lacked: it was computed entirely from the journal and its own advice trace,
    so it could report reconciliation while the broker disagreed by JPY 726.
    """
    view = journal_with_the_phantom_refund()
    self_made = BrokerSnapshot(
        asof=view.asof,
        cash=view.cash,
        positions={
            "1306.T": BrokerPosition("1306.T", 100, 437.8, 43_780.0),
            "1568.T": BrokerPosition("1568.T", 60, 1052.5, 63_150.0),
        },
        total_assets=view.cash + 106_930.0,
        source="derived_from_journal",
        mark_time=view.mark_time,
    )
    verdict = reconcile_against_broker(view, self_made)
    assert verdict.state == MISMATCH
    assert "source" in (verdict.reason or "")
    assert verdict.may_write_official_nav is False


# ---------------------------------------------------------------------------
# The actual 2026-08-14 failure
# ---------------------------------------------------------------------------
def test_the_2026_08_14_state_is_a_mismatch_not_a_reconciliation():
    verdict = reconcile_against_broker(journal_with_the_phantom_refund(), sbi_2026_08_14())
    assert verdict.state == MISMATCH
    cash_diff = next(d for d in verdict.differences if d["field"] == "cash")
    assert cash_diff["journal"] == 287_794.0
    assert cash_diff["broker"] == 287_068.0
    assert cash_diff["difference"] == pytest.approx(726.0)
    assert verdict.may_write_official_nav is False
    assert verdict.may_compute_return_metrics is False


def test_a_mismatch_never_proposes_a_balancing_adjustment():
    """The one thing this system must never do is invent the missing entry."""
    verdict = reconcile_against_broker(journal_with_the_phantom_refund(), sbi_2026_08_14())
    payload = verdict.to_dict()
    text = repr(payload).lower()
    assert "adjustment" not in text
    assert "suggested_entry" not in payload
    assert payload.get("proposed_correction") is None
    assert verdict.difference_is_not_an_instruction is True


def test_quantity_mismatch_is_reported_per_symbol():
    view = JournalView(
        asof=date(2026, 8, 14),
        cash=287_068.0,
        quantities={"1306.T": 100, "1568.T": 60, "8035.T": 1},  # stale phantom
        mark_time="2026-08-14T15:30+09:00",
    )
    verdict = reconcile_against_broker(view, sbi_2026_08_14())
    assert verdict.state == MISMATCH
    qty_diff = next(d for d in verdict.differences if d["field"] == "quantity:8035.T")
    assert qty_diff["journal"] == 1
    assert qty_diff["broker"] == 0


# ---------------------------------------------------------------------------
# Staleness and mark-time comparability
# ---------------------------------------------------------------------------
def test_an_old_snapshot_is_stale_not_reconciled():
    old = sbi_2026_08_14()
    view = JournalView(
        asof=date(2026, 8, 20),
        cash=287_068.0,
        quantities={"1306.T": 100, "1568.T": 60},
        mark_time="2026-08-20T15:30+09:00",
    )
    verdict = reconcile_against_broker(view, old, max_staleness_days=1)
    assert verdict.state == STALE
    assert verdict.may_write_official_nav is False


def test_navs_struck_at_different_times_are_incomparable():
    """Comparing an intraday broker total with an EOD journal NAV proves nothing."""
    view = JournalView(
        asof=date(2026, 8, 14),
        cash=287_068.0,
        quantities={"1306.T": 100, "1568.T": 60},
        mark_time="2026-08-14T11:30+09:00",  # morning session
    )
    verdict = reconcile_against_broker(view, sbi_2026_08_14())
    assert verdict.state == INCOMPARABLE_MARK_TIME
    assert verdict.may_write_official_nav is False
    # Cash and quantities are still worth reporting; only NAV is incomparable.
    assert verdict.comparable_fields == ["cash", "quantity"]


# ---------------------------------------------------------------------------
# Provisional cash: screenshots and broken tables are not money
# ---------------------------------------------------------------------------
def _cash_event(amount, provenance, provisional=None):
    entry = {
        "_type": "cash_event",
        "entry_id": f"e{abs(hash((amount, provenance)))%10**12:012d}",
        "amount": amount,
        "reason": "other",
        "source": "manual",
        "provenance": provenance,
        "ts": "2026-08-14T00:00:00+09:00",
    }
    if provisional is not None:
        entry["provisional"] = provisional
    return entry


def test_a_cash_event_read_off_a_broken_table_is_provisional():
    """The 991 case: the figure came from a table that had lost its structure."""
    events = [_cash_event(991.0, "broken_table_text")]
    result = canonical_cash(events, opening_cash=286_803.0)
    assert result["canonical_cash"] == 286_803.0, "provisional money must not be spendable"
    assert result["provisional_total"] == 991.0
    assert [e["entry_id"] for e in result["provisional_events"]] == [
        events[0]["entry_id"]
    ]


@pytest.mark.parametrize("provenance", ["screenshot", "ocr", "broken_table_text"])
def test_every_unstructured_provenance_is_provisional(provenance):
    result = canonical_cash([_cash_event(991.0, provenance)], opening_cash=0.0)
    assert result["canonical_cash"] == 0.0
    assert result["provisional_total"] == 991.0


def test_a_structured_statement_event_is_canonical():
    result = canonical_cash(
        [_cash_event(991.0, "broker_statement_csv")], opening_cash=286_803.0
    )
    assert result["canonical_cash"] == 287_794.0
    assert result["provisional_total"] == 0.0


def test_provisional_is_promoted_only_by_an_account_balance_check():
    events = [_cash_event(991.0, "broken_table_text")]
    # Broker balance disagrees -> stays provisional.
    result = canonical_cash(events, opening_cash=286_803.0, broker_cash=287_068.0)
    assert result["canonical_cash"] == 286_803.0
    assert result["promoted"] == []
    assert result["balance_check"]["agrees"] is False

    # Broker balance agrees with the event applied -> promoted.
    result = canonical_cash(events, opening_cash=286_803.0, broker_cash=287_794.0)
    assert result["canonical_cash"] == 287_794.0
    assert result["promoted"] == [events[0]["entry_id"]]
    assert result["balance_check"]["agrees"] is True


def test_an_explicit_provisional_flag_is_honoured_whatever_the_provenance():
    result = canonical_cash(
        [_cash_event(991.0, "broker_statement_csv", provisional=True)], opening_cash=0.0
    )
    assert result["canonical_cash"] == 0.0
    assert result["provisional_total"] == 991.0


# ---------------------------------------------------------------------------
# The state set itself
# ---------------------------------------------------------------------------
def test_every_declared_state_is_reachable_and_distinct():
    states = {MISSING_BROKER_SNAPSHOT, STALE, INCOMPARABLE_MARK_TIME, MISMATCH, RECONCILED}
    assert len(states) == 5
    # Only the reconciled state may unlock account-level metrics.
    from hot_theme_rotator.portfolio.broker_reconciliation import STATES_ALLOWING_OFFICIAL_NAV

    assert STATES_ALLOWING_OFFICIAL_NAV == frozenset({RECONCILED})


# ---------------------------------------------------------------------------
# The scorecard must not call absence-of-contradiction "reconciled"
# ---------------------------------------------------------------------------
def test_the_scorecard_state_name_does_not_claim_reconciliation():
    """A name is an interface. `reconciled_*` was read as reconciled.

    The scorecard's own docstring was always honest - "Positive proof of
    reconciliation does not exist in this repository ... Absence of
    contradiction is not positive confirmation" - but the STATE was called
    `reconciled_no_contradicting_evidence`, and a state name travels further
    than a docstring. It gated the account metrics, so on 2026-08-14 the
    scorecard reported a reconciled ledger while the broker disagreed by
    JPY 726.
    """
    source = (PROJECT_ROOT / "tools" / "three_ledger_scorecard.py").read_text(encoding="utf-8")
    assert "reconciled_no_contradicting_evidence" not in source, (
        "the state name still claims reconciliation it cannot establish"
    )
    assert "no_contradicting_journal_evidence" in source
    # And it must say out loud what it is not.
    assert "external" in source.lower()
