\
"""Publish reports into an Obsidian vault folder.

- Copies Plotly HTML files generated by ss6_sqlite.py into a dated folder under your vault.
- Generates a Markdown report that embeds the HTML via iframe (and also provides links).

Example (your vault):
  python report_obsidian.py --vault "E:\quantum\quantum investment" --report_dir reports --asof 2026-02-01
"""
from __future__ import annotations

import argparse
from datetime import date
from pathlib import Path
import shutil
import json

DEFAULT_REPORT_FILES = [
    "strategy_report.html",
    "strategy_report_extras.html",
    "weights_heatmap.html",
]

def publish(vault: str, report_dir: str, asof: str | None = None, section: str = "Quant/Reports") -> Path:
    asof = asof or date.today().strftime("%Y-%m-%d")
    vault_path = Path(vault)
    src_dir = Path(report_dir)

    if not vault_path.exists():
        raise FileNotFoundError(f"Vault path not found: {vault_path}")

    dst_dir = vault_path / section / asof
    dst_dir.mkdir(parents=True, exist_ok=True)

    copied = []
    for fn in DEFAULT_REPORT_FILES:
        src = src_dir / fn
        if src.exists():
            shutil.copy2(src, dst_dir / fn)
            copied.append(fn)

    # Generate Markdown
    md = dst_dir / "report.md"
    frontmatter = {
        "date": asof,
        "source": "ss6_sqlite",
        "files": copied,
        "folder": str(dst_dir),
    }
    md_text = "---\n" + "\n".join([f"{k}: {json.dumps(v, ensure_ascii=False) if isinstance(v, (list, dict)) else v}" for k, v in frontmatter.items()]) + "\n---\n\n"
    md_text += f"# Backtest Report ({asof})\n\n"
    md_text += "## Files\n\n"
    for fn in copied:
        md_text += f"- [{fn}]({fn})\n"
    md_text += "\n## Embedded (Preview)\n\n"
    # Obsidian preview renders HTML; iframe works on desktop for local vault files
    for fn in copied:
        md_text += f"### {fn}\n\n"
        md_text += f'<iframe src="{fn}" width="100%" height="900"></iframe>\n\n'
        md_text += f'![[{fn}]]\n\n'  # optional: if your Obsidian setup supports HTML embedding
    md.write_text(md_text, encoding="utf-8")

    return md

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--vault", required=True)
    ap.add_argument("--report_dir", default="reports")
    ap.add_argument("--asof", default=None)
    ap.add_argument("--section", default="Quant/Reports")
    args = ap.parse_args()

    md = publish(args.vault, args.report_dir, args.asof, args.section)
    print(f"✅ Published: {md}")
