import { validateFinalResultPackage } from "../final_result_packager.js";
import { makeDirectReplyResponse, makeErrorResponse } from "./response_protocol.js";

/**
 * Adapts a final result package into a format suitable for Discord (or API) direct reply.
 * Converts the final artifacts into a structured text message summarizing the results.
 * 
 * @param {Object} args
 * @param {Object} args.finalResultPackage The package generated by buildFinalResultPackage
 * @param {Object} args.taskEnvelope The original routing task envelope
 * @returns {Object} DispatchSuccessResponse (response_mode: 'direct_reply')
 */
export function buildDiscordCompletionReply({ finalResultPackage, taskEnvelope }) {
  if (!finalResultPackage || !taskEnvelope) {
    throw new Error("finalResultPackage and taskEnvelope are required");
  }

  const validation = validateFinalResultPackage(finalResultPackage);
  if (!validation.ok) {
    return makeErrorResponse({
      run_id: finalResultPackage.run_id || "unknown",
      error: `Invalid final result package: ${validation.errors.join("; ")}`,
      error_code: "INVALID_RESULT_PACKAGE",
      task_envelope: taskEnvelope,
    });
  }

  const { run_id, workflow_run_id, status, artifacts, summary } = finalResultPackage;

  let replyText = `**Workflow Completed:** \`${workflow_run_id}\`\n**Status:** \`${status}\`\n\n`;

  if (summary) {
    replyText += `**Summary:**\n${summary}\n\n`;
  }

  if (artifacts && artifacts.length > 0) {
    replyText += `**Generated Artifacts (${artifacts.length}):**\n`;
    for (const art of artifacts) {
      replyText += `- **${art.label}**: \`${art.path}\`\n`;
    }
  } else {
    replyText += `*No artifacts were generated during this run.*\n`;
  }

  return makeDirectReplyResponse({
    run_id,
    task_envelope: taskEnvelope,
    reply: replyText.trim(),
  });
}
