"""P10-06 LLM Per-Ticker Brief generator.

Builds a Chinese narrative brief describing the current factual state of a
single ticker: latest price, portfolio status, screener context, ladder
references. As P10-03/04/05 land, news / factors / fundamentals can be added
via the optional fields on ``PerTickerBriefInput`` without breaking the
output schema.

Rule 8.3.1 + 13.4 governance:

- The narrative is generated by an ``LlmClient`` (Protocol from
  ``reflection_brief``), then post-checked against ``forbidden_pattern``:
  ``\\d+%`` / "胜率" / "概率" / "win rate" / "probability" / "likelihood".
- On first violation, regenerate once. Second violation → fail-closed
  (``PerTickerBriefError``).
- Numerical claims come from upstream Python (latest_close, qty, avg_cost…)
  and live in ``factual_grounding``; the LLM only weaves them into prose.
- Output schema deliberately excludes any "score" / "probability" /
  "win_rate" field so the brief cannot launder a hidden score channel.

The 24h cache + fail-closed-on-unreachable behavior is inherited from
``OllamaClient`` — this module is LLM-backend-agnostic and accepts any
``LlmClient`` implementation.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Mapping, Optional

from hot_theme_rotator.llm.reflection_brief import (
    LlmClient,
    forbidden_pattern,
    regex_check_narrative,
)


__all__ = [
    "DEFAULT_MODEL",
    "DebateBrief",
    "DebateLeg",
    "PerTickerBrief",
    "PerTickerBriefError",
    "PerTickerBriefInput",
    "generate_debate_brief",
    "generate_per_ticker_brief",
]


DEFAULT_MODEL = "gemma4:e4b"
MAX_REGEN_ATTEMPTS = 1
MAX_NARRATIVE_CHARS = 600


class PerTickerBriefError(RuntimeError):
    """Raised when the brief cannot be safely produced (LLM failure, regex
    fail-closed, or invalid input)."""


@dataclass(frozen=True)
class PerTickerBriefInput:
    """All factual inputs the brief composes from. Numerical claims listed
    here flow into ``factual_grounding`` verbatim — the LLM only weaves them
    into prose, never regenerates them.

    P10-03/04/05 land later; ``news`` / ``factors`` / ``fundamentals`` are
    accepted now as Optional so the module is forward-compatible without
    a schema bump."""

    ticker: str
    latest_close: float
    latest_asof: str
    portfolio: Optional[Mapping[str, Any]] = None
    screener: Optional[Mapping[str, Any]] = None
    ladder: Optional[Mapping[str, Any]] = None
    news: tuple[Mapping[str, Any], ...] = ()
    factors: Optional[Mapping[str, Any]] = None
    fundamentals: Optional[Mapping[str, Any]] = None
    # P3.2 — optional user-supplied context (50 chars max). Must pass the
    # SAME forbidden_pattern regex as the LLM output before concatenation.
    # Rule 8.3.1 bidirectional gate.
    user_context: str = ""


@dataclass(frozen=True)
class PerTickerBrief:
    """Structured per-ticker brief. No probability / win-rate / score field
    by design — those cannot exist anywhere in the output, even in a
    custom-named slot."""

    ticker: str
    narrative: str
    factual_grounding: tuple[str, ...]
    model_version: str
    generation_ts: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "ticker": self.ticker,
            "narrative": self.narrative,
            "factual_grounding": list(self.factual_grounding),
            "model_version": self.model_version,
            "generation_ts": self.generation_ts,
        }


def generate_per_ticker_brief(
    payload: PerTickerBriefInput,
    *,
    llm: LlmClient,
    model: str = DEFAULT_MODEL,
) -> PerTickerBrief:
    """Produce a brief for ``payload`` using ``llm`` for the narrative.

    Pipeline:
    1. Build the deterministic prompt + factual grounding from ``payload``.
    2. Call ``llm.generate`` once; scan narrative for forbidden tokens.
    3. On violation, regenerate ONCE with an explicit no-tokens directive
       (Rule 8.3.1). Second violation → raise ``PerTickerBriefError``.
    4. Scan ALL output fields (not just narrative) for forbidden tokens —
       defense-in-depth against any future schema additions that might leak.
    """
    if not isinstance(payload, PerTickerBriefInput):
        raise PerTickerBriefError("payload must be a PerTickerBriefInput")
    if not isinstance(payload.ticker, str) or not payload.ticker.strip():
        raise PerTickerBriefError("ticker must be a non-empty string")
    if not isinstance(payload.latest_close, (int, float)) or payload.latest_close <= 0:
        raise PerTickerBriefError(
            f"latest_close must be a positive number, got {payload.latest_close!r}"
        )

    # P3.2 + Rule 8.3.1 bidirectional gate — user-supplied context must
    # itself pass the forbidden_pattern regex. Otherwise a user prompt
    # like "胜率多少?" would launder a probability claim through the model.
    if payload.user_context:
        if len(payload.user_context) > 200:
            raise PerTickerBriefError(
                f"user_context too long ({len(payload.user_context)} chars, "
                "max 200); reject to avoid prompt-injection surface"
            )
        violations = regex_check_narrative(payload.user_context)
        if violations:
            raise PerTickerBriefError(
                f"user_context contains forbidden tokens {violations!r}; "
                "Rule 8.3.1 bidirectional gate — user input MUST pass the same "
                "regex as LLM output. Rephrase without probability/win-rate language."
            )

    grounding = _build_factual_grounding(payload)
    prompt = _build_prompt(payload=payload, model=model, grounding=grounding)

    narrative = _attempt_generation(llm, prompt=prompt, model=model)
    violations = regex_check_narrative(narrative)
    if violations:
        narrative = _attempt_generation(
            llm,
            prompt=(
                prompt
                + "\n\n重新生成：上一版包含禁止 token "
                + repr(violations)
                + "。严格删除所有概率/胜率/百分比表达，只保留描述性中文叙事。"
            ),
            model=model,
        )
        new_violations = regex_check_narrative(narrative)
        if new_violations:
            raise PerTickerBriefError(
                f"narrative contains forbidden tokens after one regenerate: "
                f"{new_violations!r}; Rule 8.3.1 + Rule 13.4 fail-closed"
            )

    brief = PerTickerBrief(
        ticker=payload.ticker,
        narrative=narrative,
        factual_grounding=grounding,
        model_version=model,
        generation_ts=datetime.now(tz=timezone.utc).isoformat(),
    )

    leaks = _scan_brief_for_forbidden_tokens(brief)
    if leaks:
        raise PerTickerBriefError(
            f"non-narrative brief field contains forbidden tokens {leaks!r}; "
            f"Rule 8.3.1 + Rule 13.4 fail-closed"
        )
    return brief


@dataclass(frozen=True)
class DebateLeg:
    """One leg of a Bull/Bear/Judge debate brief.

    Rule 8.3.1 multi-leg carve-out — each leg is scanned by forbidden_pattern
    INDEPENDENTLY. No leg may be marked speculative_bypass. Per-leg fail-closed.
    """
    role: str             # "bull" | "bear" | "judge"
    narrative: str
    factual_grounding: tuple[str, ...]


@dataclass(frozen=True)
class DebateBrief:
    """Multi-leg debate brief (TradingAgents-inspired)."""
    ticker: str
    bull: DebateLeg
    bear: DebateLeg
    judge: DebateLeg
    model_version: str
    generation_ts: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "ticker": self.ticker,
            "bull": {
                "role": self.bull.role,
                "narrative": self.bull.narrative,
                "factual_grounding": list(self.bull.factual_grounding),
            },
            "bear": {
                "role": self.bear.role,
                "narrative": self.bear.narrative,
                "factual_grounding": list(self.bear.factual_grounding),
            },
            "judge": {
                "role": self.judge.role,
                "narrative": self.judge.narrative,
                "factual_grounding": list(self.judge.factual_grounding),
            },
            "model_version": self.model_version,
            "generation_ts": self.generation_ts,
        }


def generate_debate_brief(
    payload: PerTickerBriefInput,
    *,
    llm: LlmClient,
    model: str = DEFAULT_MODEL,
) -> DebateBrief:
    """Produce Bull / Bear / Judge legs for ``payload``.

    Rule 8.3.1 multi-leg carve-out:
    - Each leg is scanned by forbidden_pattern independently
    - No leg may be marked speculative_bypass
    - Per-leg fail-closed: leg violating regex twice raises PerTickerBriefError
    """
    if not isinstance(payload, PerTickerBriefInput):
        raise PerTickerBriefError("payload must be a PerTickerBriefInput")
    if payload.user_context:
        if len(payload.user_context) > 200:
            raise PerTickerBriefError(
                f"user_context too long ({len(payload.user_context)} chars, max 200)"
            )
        violations = regex_check_narrative(payload.user_context)
        if violations:
            raise PerTickerBriefError(
                f"user_context contains forbidden tokens {violations!r}; "
                "Rule 8.3.1 bidirectional gate (multi-leg variant)"
            )

    grounding = _build_factual_grounding(payload)

    bull = _generate_leg(
        llm=llm, model=model, role="bull",
        directive=(
            "你是 Bull leg — 用事实证据论证当前 ticker 的看多论点（流动性/动量/估值/催化）。"
            "禁止使用胜率/概率/%/likelihood 等 Rule 8.3.1 禁止 token。"
        ),
        payload=payload, grounding=grounding,
    )
    bear = _generate_leg(
        llm=llm, model=model, role="bear",
        directive=(
            "你是 Bear leg — 用事实证据论证当前 ticker 的看空论点（动量衰减/估值过热/风险点）。"
            "禁止使用胜率/概率/%/likelihood 等 Rule 8.3.1 禁止 token。"
        ),
        payload=payload, grounding=grounding,
    )
    judge = _generate_leg(
        llm=llm, model=model, role="judge",
        directive=(
            "你是 Judge — 综合 Bull / Bear 双方观点，给出当前状态的描述性结论。"
            "禁止给出买卖建议、禁止使用胜率/概率/%/likelihood 等 Rule 8.3.1 禁止 token。"
            "你的判断必须 conditional：'under reconstructed evidence' 而非 'is'。"
        ),
        payload=payload, grounding=grounding,
        extra_context=f"\nBull leg said: {bull.narrative}\nBear leg said: {bear.narrative}",
    )

    return DebateBrief(
        ticker=payload.ticker,
        bull=bull, bear=bear, judge=judge,
        model_version=model,
        generation_ts=datetime.now(tz=timezone.utc).isoformat(),
    )


def _generate_leg(
    *,
    llm: LlmClient,
    model: str,
    role: str,
    directive: str,
    payload: PerTickerBriefInput,
    grounding: tuple[str, ...],
    extra_context: str = "",
) -> DebateLeg:
    """Per-leg generation with Rule 8.3.1 fail-closed regex check."""
    grounding_block = "\n".join(f"- {g}" for g in grounding)
    user_block = (
        f"\n用户额外上下文 (已通过 Rule 8.3.1 反向 regex):\n{payload.user_context}\n"
        if payload.user_context else ""
    )
    base_prompt = (
        f"任务：为 ticker {payload.ticker} 写一段 {role} leg 的中文叙事综合。\n"
        f"{directive}\n"
        f"硬性规则：字数上限 {MAX_NARRATIVE_CHARS} 字 · 不发明 grounding 外的数字 · "
        "用 markdown 段落 · 不要标题。\n"
        f"事实证据：\n{grounding_block}\n"
        + user_block + extra_context
        + f"\n模型: {model}\n"
    )
    narrative = _attempt_generation(llm, prompt=base_prompt, model=model)
    violations = regex_check_narrative(narrative)
    if violations:
        narrative = _attempt_generation(
            llm,
            prompt=(
                base_prompt + "\n\n重新生成：上一版包含禁止 token "
                + repr(violations) + "。严格删除概率/胜率/%/likelihood 表达。"
            ),
            model=model,
        )
        new_violations = regex_check_narrative(narrative)
        if new_violations:
            raise PerTickerBriefError(
                f"{role} leg contains forbidden tokens after one regenerate: "
                f"{new_violations!r}; Rule 8.3.1 multi-leg per-leg fail-closed"
            )
    return DebateLeg(role=role, narrative=narrative, factual_grounding=grounding)


# ─── internals ──────────────────────────────────────────────────────────────


def _attempt_generation(llm: LlmClient, *, prompt: str, model: str) -> str:
    try:
        text = llm.generate(prompt=prompt, model=model)
    except Exception as exc:  # noqa: BLE001
        raise PerTickerBriefError(
            f"LLM client failed: {type(exc).__name__}: {exc}"
        ) from exc
    if not isinstance(text, str) or not text.strip():
        raise PerTickerBriefError("LLM returned empty narrative")
    return text


def _build_factual_grounding(payload: PerTickerBriefInput) -> tuple[str, ...]:
    items: list[str] = [
        f"ticker={payload.ticker}",
        f"latest_close=¥{payload.latest_close:.2f}",
        f"latest_asof={payload.latest_asof}",
    ]
    if payload.portfolio:
        p = payload.portfolio
        if p.get("qty") is not None:
            items.append(f"position_qty={p['qty']}")
        if p.get("avg_cost") is not None:
            items.append(f"position_avg_cost=¥{float(p['avg_cost']):.2f}")
        if p.get("market_value") is not None:
            items.append(f"position_market_value=¥{float(p['market_value']):.2f}")
        if p.get("unrealized_pnl") is not None:
            items.append(f"position_unrealized_pnl=¥{float(p['unrealized_pnl']):.2f}")
    if payload.screener:
        s = payload.screener
        # score is an uncalibrated_research_score — pass through as raw float,
        # let the LLM describe it as "screener research score" (NOT win rate).
        if s.get("score") is not None:
            items.append(f"screener_research_score={float(s['score']):.4f}")
        if s.get("mom_20") is not None:
            items.append(f"mom_20={float(s['mom_20']):.4f}")
        if s.get("mom_60") is not None:
            items.append(f"mom_60={float(s['mom_60']):.4f}")
        if s.get("sharpe_20") is not None:
            items.append(f"sharpe_20={float(s['sharpe_20']):.4f}")
        if s.get("adv") is not None:
            items.append(f"adv={float(s['adv']):.0f}")
    if payload.ladder:
        ref = payload.ladder.get("ref_price")
        if ref is not None:
            items.append(f"ladder_ref_price=¥{float(ref):.2f}")
        tiers = payload.ladder.get("tiers") or ()
        for t in tiers:
            kind = t.get("kind", "?")
            price = t.get("price")
            if price is not None:
                items.append(f"ladder_{kind}=¥{float(price):.2f}")
    if payload.news:
        items.append(f"news_count={len(payload.news)}")
        for i, n in enumerate(payload.news[:3]):
            headline = str(n.get("headline", "")).strip()
            if headline:
                items.append(f"news_{i}_headline={headline[:80]}")
    if payload.factors:
        for k, v in payload.factors.items():
            items.append(f"factor_{k}={v}")
    if payload.fundamentals:
        for k, v in payload.fundamentals.items():
            items.append(f"fundamental_{k}={v}")
    return tuple(items)


def _build_prompt(
    *,
    payload: PerTickerBriefInput,
    model: str,
    grounding: tuple[str, ...],
) -> str:
    grounding_block = "\n".join(f"- {g}" for g in grounding)
    user_block = (
        f"\n用户额外上下文 (已通过 Rule 8.3.1 反向 regex 检查):\n{payload.user_context}\n"
        if payload.user_context else ""
    )
    return (
        "你是单用户量化系统的中文研究助手。任务：把下列事实编成一段简短的中文叙事综合。\n"
        "硬性输出规则：\n"
        f"- 字数上限 {MAX_NARRATIVE_CHARS} 中文字符。\n"
        "- 只描述当前事实状态，禁止任何买入/卖出/加仓/减仓/止损/止盈建议。\n"
        "- 禁止任何百分比数字（不能出现 \\d+%、'percent'、'pct'）。\n"
        "- 禁止 '胜率' / '概率' / 'win rate' / 'probability' / 'likelihood' 字样。\n"
        "- 不要发明任何 grounding 里没有的数字。\n"
        "- 引用数字时按名字（例如 '当前价' '持仓数量'），不要重复数值。\n"
        "- 用 markdown 段落，不需要标题。\n"
        "事实证据：\n"
        f"{grounding_block}\n"
        + user_block
        + f"模型: {model}\n"
    )


def _scan_brief_for_forbidden_tokens(brief: PerTickerBrief) -> list[str]:
    """Defense-in-depth: scan every string field on the brief for forbidden
    tokens, not just ``narrative``. Mirrors reflection_brief.scan_brief_for_
    forbidden_tokens."""
    violations: list[str] = []
    violations.extend(regex_check_narrative(brief.narrative))
    for s in brief.factual_grounding:
        if isinstance(s, str):
            violations.extend(regex_check_narrative(s))
    return violations
