"""P10-06 LLM Per-Ticker Brief generator.

Builds a Chinese narrative brief describing the current factual state of a
single ticker: latest price, portfolio status, screener context, ladder
references. As P10-03/04/05 land, news / factors / fundamentals can be added
via the optional fields on ``PerTickerBriefInput`` without breaking the
output schema.

Rule 8.3.1 + 13.4 governance:

- The narrative is generated by an ``LlmClient`` (Protocol from
  ``reflection_brief``), then post-checked against ``forbidden_pattern``:
  ``\\d+%`` / "胜率" / "概率" / "win rate" / "probability" / "likelihood".
- On first violation, regenerate once. Second violation → fail-closed
  (``PerTickerBriefError``).
- Numerical claims come from upstream Python (latest_close, qty, avg_cost…)
  and live in ``factual_grounding``; the LLM only weaves them into prose.
- Output schema deliberately excludes any "score" / "probability" /
  "win_rate" field so the brief cannot launder a hidden score channel.

The 24h cache + fail-closed-on-unreachable behavior is inherited from
``OllamaClient`` — this module is LLM-backend-agnostic and accepts any
``LlmClient`` implementation.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Mapping, Optional

from hot_theme_rotator.llm.reflection_brief import (
    LlmClient,
    forbidden_pattern,
    regex_check_narrative,
)


__all__ = [
    "DEFAULT_MODEL",
    "PerTickerBrief",
    "PerTickerBriefError",
    "PerTickerBriefInput",
    "generate_per_ticker_brief",
]


DEFAULT_MODEL = "gemma4:e4b"
MAX_REGEN_ATTEMPTS = 1
MAX_NARRATIVE_CHARS = 600


class PerTickerBriefError(RuntimeError):
    """Raised when the brief cannot be safely produced (LLM failure, regex
    fail-closed, or invalid input)."""


@dataclass(frozen=True)
class PerTickerBriefInput:
    """All factual inputs the brief composes from. Numerical claims listed
    here flow into ``factual_grounding`` verbatim — the LLM only weaves them
    into prose, never regenerates them.

    P10-03/04/05 land later; ``news`` / ``factors`` / ``fundamentals`` are
    accepted now as Optional so the module is forward-compatible without
    a schema bump."""

    ticker: str
    latest_close: float
    latest_asof: str
    portfolio: Optional[Mapping[str, Any]] = None
    screener: Optional[Mapping[str, Any]] = None
    ladder: Optional[Mapping[str, Any]] = None
    news: tuple[Mapping[str, Any], ...] = ()
    factors: Optional[Mapping[str, Any]] = None
    fundamentals: Optional[Mapping[str, Any]] = None


@dataclass(frozen=True)
class PerTickerBrief:
    """Structured per-ticker brief. No probability / win-rate / score field
    by design — those cannot exist anywhere in the output, even in a
    custom-named slot."""

    ticker: str
    narrative: str
    factual_grounding: tuple[str, ...]
    model_version: str
    generation_ts: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "ticker": self.ticker,
            "narrative": self.narrative,
            "factual_grounding": list(self.factual_grounding),
            "model_version": self.model_version,
            "generation_ts": self.generation_ts,
        }


def generate_per_ticker_brief(
    payload: PerTickerBriefInput,
    *,
    llm: LlmClient,
    model: str = DEFAULT_MODEL,
) -> PerTickerBrief:
    """Produce a brief for ``payload`` using ``llm`` for the narrative.

    Pipeline:
    1. Build the deterministic prompt + factual grounding from ``payload``.
    2. Call ``llm.generate`` once; scan narrative for forbidden tokens.
    3. On violation, regenerate ONCE with an explicit no-tokens directive
       (Rule 8.3.1). Second violation → raise ``PerTickerBriefError``.
    4. Scan ALL output fields (not just narrative) for forbidden tokens —
       defense-in-depth against any future schema additions that might leak.
    """
    if not isinstance(payload, PerTickerBriefInput):
        raise PerTickerBriefError("payload must be a PerTickerBriefInput")
    if not isinstance(payload.ticker, str) or not payload.ticker.strip():
        raise PerTickerBriefError("ticker must be a non-empty string")
    if not isinstance(payload.latest_close, (int, float)) or payload.latest_close <= 0:
        raise PerTickerBriefError(
            f"latest_close must be a positive number, got {payload.latest_close!r}"
        )

    grounding = _build_factual_grounding(payload)
    prompt = _build_prompt(payload=payload, model=model, grounding=grounding)

    narrative = _attempt_generation(llm, prompt=prompt, model=model)
    violations = regex_check_narrative(narrative)
    if violations:
        narrative = _attempt_generation(
            llm,
            prompt=(
                prompt
                + "\n\n重新生成：上一版包含禁止 token "
                + repr(violations)
                + "。严格删除所有概率/胜率/百分比表达，只保留描述性中文叙事。"
            ),
            model=model,
        )
        new_violations = regex_check_narrative(narrative)
        if new_violations:
            raise PerTickerBriefError(
                f"narrative contains forbidden tokens after one regenerate: "
                f"{new_violations!r}; Rule 8.3.1 + Rule 13.4 fail-closed"
            )

    brief = PerTickerBrief(
        ticker=payload.ticker,
        narrative=narrative,
        factual_grounding=grounding,
        model_version=model,
        generation_ts=datetime.now(tz=timezone.utc).isoformat(),
    )

    leaks = _scan_brief_for_forbidden_tokens(brief)
    if leaks:
        raise PerTickerBriefError(
            f"non-narrative brief field contains forbidden tokens {leaks!r}; "
            f"Rule 8.3.1 + Rule 13.4 fail-closed"
        )
    return brief


# ─── internals ──────────────────────────────────────────────────────────────


def _attempt_generation(llm: LlmClient, *, prompt: str, model: str) -> str:
    try:
        text = llm.generate(prompt=prompt, model=model)
    except Exception as exc:  # noqa: BLE001
        raise PerTickerBriefError(
            f"LLM client failed: {type(exc).__name__}: {exc}"
        ) from exc
    if not isinstance(text, str) or not text.strip():
        raise PerTickerBriefError("LLM returned empty narrative")
    return text


def _build_factual_grounding(payload: PerTickerBriefInput) -> tuple[str, ...]:
    items: list[str] = [
        f"ticker={payload.ticker}",
        f"latest_close=¥{payload.latest_close:.2f}",
        f"latest_asof={payload.latest_asof}",
    ]
    if payload.portfolio:
        p = payload.portfolio
        if p.get("qty") is not None:
            items.append(f"position_qty={p['qty']}")
        if p.get("avg_cost") is not None:
            items.append(f"position_avg_cost=¥{float(p['avg_cost']):.2f}")
        if p.get("market_value") is not None:
            items.append(f"position_market_value=¥{float(p['market_value']):.2f}")
        if p.get("unrealized_pnl") is not None:
            items.append(f"position_unrealized_pnl=¥{float(p['unrealized_pnl']):.2f}")
    if payload.screener:
        s = payload.screener
        # score is an uncalibrated_research_score — pass through as raw float,
        # let the LLM describe it as "screener research score" (NOT win rate).
        if s.get("score") is not None:
            items.append(f"screener_research_score={float(s['score']):.4f}")
        if s.get("mom_20") is not None:
            items.append(f"mom_20={float(s['mom_20']):.4f}")
        if s.get("mom_60") is not None:
            items.append(f"mom_60={float(s['mom_60']):.4f}")
        if s.get("sharpe_20") is not None:
            items.append(f"sharpe_20={float(s['sharpe_20']):.4f}")
        if s.get("adv") is not None:
            items.append(f"adv={float(s['adv']):.0f}")
    if payload.ladder:
        ref = payload.ladder.get("ref_price")
        if ref is not None:
            items.append(f"ladder_ref_price=¥{float(ref):.2f}")
        tiers = payload.ladder.get("tiers") or ()
        for t in tiers:
            kind = t.get("kind", "?")
            price = t.get("price")
            if price is not None:
                items.append(f"ladder_{kind}=¥{float(price):.2f}")
    if payload.news:
        items.append(f"news_count={len(payload.news)}")
        for i, n in enumerate(payload.news[:3]):
            headline = str(n.get("headline", "")).strip()
            if headline:
                items.append(f"news_{i}_headline={headline[:80]}")
    if payload.factors:
        for k, v in payload.factors.items():
            items.append(f"factor_{k}={v}")
    if payload.fundamentals:
        for k, v in payload.fundamentals.items():
            items.append(f"fundamental_{k}={v}")
    return tuple(items)


def _build_prompt(
    *,
    payload: PerTickerBriefInput,
    model: str,
    grounding: tuple[str, ...],
) -> str:
    grounding_block = "\n".join(f"- {g}" for g in grounding)
    return (
        "你是单用户量化系统的中文研究助手。任务：把下列事实编成一段简短的中文叙事综合。\n"
        "硬性输出规则：\n"
        f"- 字数上限 {MAX_NARRATIVE_CHARS} 中文字符。\n"
        "- 只描述当前事实状态，禁止任何买入/卖出/加仓/减仓/止损/止盈建议。\n"
        "- 禁止任何百分比数字（不能出现 \\d+%、'percent'、'pct'）。\n"
        "- 禁止 '胜率' / '概率' / 'win rate' / 'probability' / 'likelihood' 字样。\n"
        "- 不要发明任何 grounding 里没有的数字。\n"
        "- 引用数字时按名字（例如 '当前价' '持仓数量'），不要重复数值。\n"
        "- 用 markdown 段落，不需要标题。\n"
        "事实证据：\n"
        f"{grounding_block}\n"
        f"模型: {model}\n"
    )


def _scan_brief_for_forbidden_tokens(brief: PerTickerBrief) -> list[str]:
    """Defense-in-depth: scan every string field on the brief for forbidden
    tokens, not just ``narrative``. Mirrors reflection_brief.scan_brief_for_
    forbidden_tokens."""
    violations: list[str] = []
    violations.extend(regex_check_narrative(brief.narrative))
    for s in brief.factual_grounding:
        if isinstance(s, str):
            violations.extend(regex_check_narrative(s))
    return violations
