"""LLM Reflection Brief generator (P11-05, Rule 8.3.1 + 13.4).

Consumes ``PitSnapshot`` + ``TraceRecord`` + ``RcaReport`` and produces a
structured Chinese research note. The narrative is generated by the LLM; the
numerical claims come from the upstream L3 (Policy Replay) + L4 (RCA) layers
and are passed through verbatim, NOT regenerated by the LLM.

Rule 8.3.1 + 13.4 enforcement (Rule 8.3 absolute): the narrative MUST NOT
contain any of:

- ``\\d+%`` numeric percentages (use phrases like "most candidates" instead)
- "胜率" / "win rate" / "概率" / "probability" / "likelihood"

Post-generation regex rejects violations. On first violation, regenerate once;
second violation → fail-closed.

Output language inherits ``counterfactual_validity`` from the upstream RCA —
the brief MUST begin with the conditional prefix from
``reflection.validity_class.conditional_language_prefix``.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Mapping, Protocol, Sequence

from hot_theme_rotator.observability.schema import PitSnapshot
from hot_theme_rotator.reflection.rca import RcaReport
from hot_theme_rotator.reflection.trace_logger import TraceRecord
from hot_theme_rotator.reflection.validity_class import (
    conditional_language_prefix,
    is_publishable,
)


__all__ = [
    "LlmClient",
    "ReflectionBrief",
    "ReflectionBriefError",
    "ReflectionBriefInput",
    "forbidden_pattern",
    "generate_reflection_brief",
    "regex_check_narrative",
    "scan_brief_for_forbidden_tokens",
]


def scan_brief_for_forbidden_tokens(brief: "ReflectionBrief") -> list[str]:
    """Patch H8: scan ALL string fields of a brief, not just ``narrative``.

    Rule 8.3.1 + 13.4 forbid probability/win-rate output ANYWHERE in the
    user-visible brief. ``factual_grounding`` / ``proposed_actions`` /
    ``confidence_caveats`` are built from upstream Python data so leakage is
    unlikely by construction, but defensive scanning here closes the
    laundering surface entirely.
    """
    violations: list[str] = []
    violations.extend(regex_check_narrative(brief.narrative))
    for s in brief.factual_grounding:
        if isinstance(s, str):
            violations.extend(regex_check_narrative(s))
    for action in brief.proposed_actions:
        for value in action.values():
            if isinstance(value, str):
                violations.extend(regex_check_narrative(value))
    for s in brief.confidence_caveats:
        if isinstance(s, str):
            violations.extend(regex_check_narrative(s))
    return violations


DEFAULT_MODEL_VERSION = "gemma4:e4b"
MAX_REGEN_ATTEMPTS = 1  # Rule 8.3.1: one regenerate after first violation


# Combined regex matching anything forbidden by Rule 8.3.1 + Rule 13.4.
# Patches H7 (2026-05-26 Codex review #3): expanded to cover written-out
# "percent"/"pct", fullwidth ％, and whitespace-tolerant CJK keywords.
_FORBIDDEN_PATTERN = re.compile(
    r"\d+(?:\.\d+)?\s*[%％]"                     # 75% / 75 % / 75％ / 0.75%
    r"|\d+(?:\.\d+)?\s*(?:percent|pct)\b"       # 75 percent / 0.75 pct
    r"|胜\s*率"                                  # 胜率 / 胜 率
    r"|概\s*率"                                  # 概率 / 概 率
    r"|win\s*rate"                               # win rate / winrate
    r"|probabilit(?:y|ies)"
    r"|likelihood",
    re.IGNORECASE,
)


def forbidden_pattern() -> re.Pattern:
    """Return the compiled regex enforcing Rule 8.3.1 + 13.4."""
    return _FORBIDDEN_PATTERN


def regex_check_narrative(narrative: str) -> list[str]:
    """Return the list of forbidden substrings present in ``narrative``."""
    if not isinstance(narrative, str):
        raise TypeError(f"narrative must be a string, got {type(narrative).__name__}")
    return [m.group(0) for m in _FORBIDDEN_PATTERN.finditer(narrative)]


class ReflectionBriefError(RuntimeError):
    """Raised when the brief cannot be safely produced."""


class LlmClient(Protocol):
    """Protocol for any narrative LLM backend (Ollama, vLLM, mock, ...)."""

    def generate(self, *, prompt: str, model: str) -> str:
        ...


@dataclass(frozen=True)
class ReflectionBriefInput:
    """All upstream evidence the brief composes."""

    snapshot: PitSnapshot
    trace: TraceRecord
    rca: RcaReport


@dataclass(frozen=True)
class ReflectionBrief:
    """Structured reflection brief — narrative + numerical evidence + caveats."""

    narrative: str
    factual_grounding: tuple[str, ...]
    proposed_actions: tuple[Mapping[str, object], ...]
    confidence_caveats: tuple[str, ...]
    counterfactual_validity: str
    model_version: str
    generation_ts: str

    def to_dict(self) -> dict[str, object]:
        return {
            "narrative": self.narrative,
            "factual_grounding": list(self.factual_grounding),
            "proposed_actions": [dict(p) for p in self.proposed_actions],
            "confidence_caveats": list(self.confidence_caveats),
            "counterfactual_validity": self.counterfactual_validity,
            "model_version": self.model_version,
            "generation_ts": self.generation_ts,
        }


def generate_reflection_brief(
    payload: ReflectionBriefInput,
    *,
    llm: LlmClient,
    model: str = DEFAULT_MODEL_VERSION,
) -> ReflectionBrief:
    """Build a brief from ``payload`` using ``llm`` for the narrative.

    Steps:
    1. Build the deterministic prompt from upstream evidence.
    2. Call ``llm.generate`` once; check narrative against forbidden pattern.
    3. On violation, regenerate ONCE (Rule 8.3.1). Second violation → raise.
    4. Pass through the conditional-language prefix per validity_class.
    """
    rca = payload.rca
    snapshot = payload.snapshot
    trace = payload.trace
    validity = rca.counterfactual_validity

    prefix = conditional_language_prefix(validity)
    prompt = _build_prompt(payload=payload, model=model, prefix=prefix)

    narrative = _attempt_generation(llm, prompt=prompt, model=model)
    violations = regex_check_narrative(narrative)
    if violations:
        narrative = _attempt_generation(
            llm,
            prompt=prompt + "\n\nREGENERATE: previous output contained forbidden tokens "
                            f"{violations!r}. Strictly remove all such tokens.",
            model=model,
        )
        new_violations = regex_check_narrative(narrative)
        if new_violations:
            raise ReflectionBriefError(
                f"narrative contains forbidden tokens after one regenerate: "
                f"{new_violations!r}; Rule 8.3.1 + Rule 13.4 fail-closed"
            )

    if not narrative.startswith(prefix):
        # Prepend the conditional prefix if the LLM omitted it — the prefix
        # is structural, not creative.
        narrative = prefix + narrative

    # Factual grounding: numerical claims come from upstream layers, NOT from
    # the LLM. The narrative may reference them by index/name.
    grounding = _extract_factual_grounding(snapshot, trace, rca)
    proposed = _propose_actions(rca)
    caveats = _build_caveats(validity, rca)

    brief = ReflectionBrief(
        narrative=narrative,
        factual_grounding=grounding,
        proposed_actions=proposed,
        confidence_caveats=caveats,
        counterfactual_validity=validity,
        model_version=model,
        generation_ts=datetime.now(tz=timezone.utc).isoformat(),
    )
    # Patch H8: scan all output fields (not just narrative) for laundering.
    leaks = scan_brief_for_forbidden_tokens(brief)
    if leaks:
        raise ReflectionBriefError(
            f"non-narrative brief field contains forbidden tokens {leaks!r}; "
            f"Rule 8.3.1 + Rule 13.4 fail-closed (laundering via "
            f"factual_grounding/proposed_actions/caveats blocked)"
        )
    return brief


# ─── internals ──────────────────────────────────────────────────────────────


def _attempt_generation(llm: LlmClient, *, prompt: str, model: str) -> str:
    try:
        text = llm.generate(prompt=prompt, model=model)
    except Exception as exc:  # noqa: BLE001 — wrap any client failure
        raise ReflectionBriefError(
            f"LLM client failed: {type(exc).__name__}: {exc}"
        ) from exc
    if not isinstance(text, str) or not text.strip():
        raise ReflectionBriefError("LLM returned empty narrative")
    return text


def _build_prompt(
    *,
    payload: ReflectionBriefInput,
    model: str,
    prefix: str,
) -> str:
    rca = payload.rca
    primary = rca.primary_root_cause or "no_clear_intervention"
    funnel_summary = ", ".join(
        f"{s.name}={s.count}" for s in rca.funnel.stages
    )
    return (
        "You are a quantitative-research analyst writing a Chinese reflection note "
        "for a single-user advisory system. Output policy:\n"
        "- Start with this exact prefix: " + prefix + "\n"
        "- DO NOT use any numeric percentage (no \\d+%).\n"
        "- DO NOT use the words 胜率, 概率, win rate, probability, likelihood.\n"
        "- Refer to numeric evidence by name (e.g., 'the primary root cause'), not by value.\n"
        "- Keep the note <= 300 Chinese characters.\n"
        f"Validity class: {rca.counterfactual_validity}\n"
        f"Primary root cause: {primary}\n"
        f"Funnel summary: {funnel_summary}\n"
        f"Stale data attributed: {rca.stale_data_attributed}\n"
        f"Snapshot id: {payload.snapshot.snapshot_id}\n"
        f"Trace id: {payload.trace.trace_id}\n"
        f"Model: {model}\n"
    )


def _extract_factual_grounding(
    snapshot: PitSnapshot,
    trace: TraceRecord,
    rca: RcaReport,
) -> tuple[str, ...]:
    items: list[str] = [
        f"snapshot_id={snapshot.snapshot_id}",
        f"decision_cutoff={snapshot.decision_cutoff}",
        f"trace_id={trace.trace_id}",
        f"final_action={trace.final_action}",
        f"final_reason={trace.final_reason}",
        f"funnel_total_loss_ratio={rca.funnel_total_loss_ratio:.4f}",
    ]
    for c in rca.ranked_contributions:
        items.append(
            f"intervention={c.intervention} baseline={c.baseline_alerts} "
            f"ablated={c.ablated_alerts} marginal_recovery={c.marginal_recovery}"
        )
    return tuple(items)


def _propose_actions(rca: RcaReport) -> tuple[Mapping[str, object], ...]:
    """Map the primary root cause to a structured proposal stub (Rule 13.6)."""
    primary = rca.primary_root_cause
    if not primary:
        return ()
    return (
        {
            "evidence_class": "ablation",
            "intervention": primary,
            "marginal_recovery": rca.ranked_contributions[0].marginal_recovery,
            "counterfactual_validity": rca.counterfactual_validity,
            "rationale_pointer": f"see ablation contribution for {primary}",
        },
    )


def _build_caveats(validity: str, rca: RcaReport) -> tuple[str, ...]:
    caveats: list[str] = []
    if not is_publishable(validity):
        caveats.append(
            f"counterfactual_validity={validity}: no numeric conclusion may be drawn"
        )
    if rca.stale_data_attributed:
        caveats.append(
            f"stale data attributed ({rca.stale_data_days} days old, exceeds threshold)"
        )
    if not rca.ranked_contributions:
        caveats.append("no ablation contributions available")
    return tuple(caveats)
